stats_example = {
                    'name': 'Mute',
                    'ctu': 'SAS',
                    'role': 'Defender',
                    'kills': 41,
                    'deaths': 55,
                    'kd': 0.7455,
                    'wins': 30,
                    'losses': 43,
                    'wl': 0.6977,
                    'headshots': 16,
                    'dbnos': 19,
                    'melee_kills': 0,
                    'experience': 140465,
                    'playtime': 13921,
                    'abilities': [
                        {
                            'ability': 'Gadgets jammed',
                            'value': 129
                        },
                        {
                            'ability': 'Jammers deployed',
                            'value': 289
                        }
                    ],
                    'badge_image': 'https://cdn.r6stats.com/badges/mute_badge.png'
                }, {'name': 'Smoke', 'ctu': 'SAS', 'role': 'Defender', 'kills': 201, 'deaths': 340, 'kd': 0.5912,
                    'wins': 239, 'losses': 233, 'wl': 1.0258, 'headshots': 66, 'dbnos': 88, 'melee_kills': 1,
                    'experience': 753580, 'playtime': 86951,
                    'abilities': [{'ability': 'Kills with Poison Gas', 'value': 16}],
                    'badge_image': 'https://cdn.r6stats.com/badges/smoke_badge.png'}, {'name': 'Sledge', 'ctu': 'SAS',
                                                                                       'role': 'Attacker', 'kills': 167,
                                                                                       'deaths': 214, 'kd': 0.7804,
                                                                                       'wins': 127, 'losses': 150,
                                                                                       'wl': 0.8467, 'headshots': 47,
                                                                                       'dbnos': 67, 'melee_kills': 4,
                                                                                       'experience': 561115,
                                                                                       'playtime': 51803, 'abilities': [
        {'ability': 'Destruction by Breaching Hammer', 'value': 352},
        {'ability': 'Kills with Breaching Hammer', 'value': 0}],
                                                                                       'badge_image': 'https://cdn.r6stats.com/badges/sledge_badge.png'}, {
                    'name': 'Thatcher', 'ctu': 'SAS', 'role': 'Attacker', 'kills': 111, 'deaths': 218, 'kd': 0.5092,
                    'wins': 129, 'losses': 132, 'wl': 0.9773, 'headshots': 38, 'dbnos': 44, 'melee_kills': 1,
                    'experience': 414335, 'playtime': 49731,
                    'abilities': [{'ability': 'Gadgets destroyed with EMP', 'value': 0}],
                    'badge_image': 'https://cdn.r6stats.com/badges/thatcher_badge.png'}, {'name': 'Castle',
                                                                                          'ctu': 'FBI SWAT',
                                                                                          'role': 'Defender',
                                                                                          'kills': 3, 'deaths': 6,
                                                                                          'kd': 0.5, 'wins': 5,
                                                                                          'losses': 1, 'wl': 5,
                                                                                          'headshots': 1, 'dbnos': 1,
                                                                                          'melee_kills': 0,
                                                                                          'experience': 11210,
                                                                                          'playtime': 1206,
                                                                                          'abilities': [{
                                                                                                            'ability': 'Kevlar Barricades deployed',
                                                                                                            'value': 21}],
                                                                                          'badge_image': 'https://cdn.r6stats.com/badges/castle_badge.png'}, {
                    'name': 'Ash', 'ctu': 'FBI SWAT', 'role': 'Attacker', 'kills': 102, 'deaths': 186, 'kd': 0.5484,
                    'wins': 100, 'losses': 123, 'wl': 0.813, 'headshots': 43, 'dbnos': 43, 'melee_kills': 0,
                    'experience': 377155, 'playtime': 40580,
                    'abilities': [{'ability': 'Kills with Breaching Round', 'value': 2},
                                  {'ability': 'Walls breached with Breaching Round', 'value': 90}],
                    'badge_image': 'https://cdn.r6stats.com/badges/ash_badge.png'}, {'name': 'Thermite',
                                                                                     'ctu': 'FBI SWAT',
                                                                                     'role': 'Attacker', 'kills': 24,
                                                                                     'deaths': 59, 'kd': 0.4068,
                                                                                     'wins': 30, 'losses': 39,
                                                                                     'wl': 0.7692, 'headshots': 6,
                                                                                     'dbnos': 6, 'melee_kills': 0,
                                                                                     'experience': 127940,
                                                                                     'playtime': 13066, 'abilities': [
        {'ability': 'Thermal Charges deployed', 'value': 32}, {'ability': 'Kills with Thermal Charge', 'value': 0},
        {'ability': 'Reinforcements breached', 'value': 24}],
                                                                                     'badge_image': 'https://cdn.r6stats.com/badges/thermite_badge.png'}, {
                    'name': 'Pulse', 'ctu': 'FBI SWAT', 'role': 'Defender', 'kills': 20, 'deaths': 42, 'kd': 0.4762,
                    'wins': 29, 'losses': 26, 'wl': 1.1154, 'headshots': 5, 'dbnos': 9, 'melee_kills': 0,
                    'experience': 86315, 'playtime': 10521,
                    'abilities': [{'ability': 'Heartbeat Scanner assists', 'value': 3},
                                  {'ability': 'Enemies spotted by Heartbeat Scanner', 'value': 53}],
                    'badge_image': 'https://cdn.r6stats.com/badges/pulse_badge.png'}, {'name': 'Twitch', 'ctu': 'GIGN',
                                                                                       'role': 'Attacker', 'kills': 270,
                                                                                       'deaths': 341, 'kd': 0.7918,
                                                                                       'wins': 213, 'losses': 253,
                                                                                       'wl': 0.8419, 'headshots': 131,
                                                                                       'dbnos': 107, 'melee_kills': 0,
                                                                                       'experience': 867655,
                                                                                       'playtime': 88666, 'abilities': [
        {'ability': 'Gadgets destroyed by Shock Drone', 'value': 236},
        {'ability': 'Kills with Shock Drone', 'value': 1}],
                                                                                       'badge_image': 'https://cdn.r6stats.com/badges/twitch_badge.png'}, {
                    'name': 'Montagne', 'ctu': 'GIGN', 'role': 'Attacker', 'kills': 7, 'deaths': 24, 'kd': 0.2917,
                    'wins': 15, 'losses': 18, 'wl': 0.8333, 'headshots': 1, 'dbnos': 3, 'melee_kills': 0,
                    'experience': 56980, 'playtime': 6364,
                    'abilities': [{'ability': 'Damage blocked by Shield', 'value': 327}],
                    'badge_image': 'https://cdn.r6stats.com/badges/montagne_badge.png'}, {'name': 'Doc', 'ctu': 'GIGN',
                                                                                          'role': 'Defender',
                                                                                          'kills': 16, 'deaths': 34,
                                                                                          'kd': 0.4706, 'wins': 14,
                                                                                          'losses': 26, 'wl': 0.5385,
                                                                                          'headshots': 9, 'dbnos': 4,
                                                                                          'melee_kills': 0,
                                                                                          'experience': 68360,
                                                                                          'playtime': 7509,
                                                                                          'abilities': [{
                                                                                                            'ability': 'Hostages revived',
                                                                                                            'value': 0},
                                                                                                        {
                                                                                                            'ability': 'Self revives',
                                                                                                            'value': 5},
                                                                                                        {
                                                                                                            'ability': 'Teammates revived',
                                                                                                            'value': 2}],
                                                                                          'badge_image': 'https://cdn.r6stats.com/badges/doc_badge.png'}, {
                    'name': 'Rook', 'ctu': 'GIGN', 'role': 'Defender', 'kills': 60, 'deaths': 58, 'kd': 1.0345,
                    'wins': 47, 'losses': 33, 'wl': 1.4242, 'headshots': 24, 'dbnos': 24, 'melee_kills': 0,
                    'experience': 185170, 'playtime': 15912,
                    'abilities': [{'ability': 'Armor Crates deployed', 'value': 269},
                                  {'ability': 'Armors taken for self', 'value': 80},
                                  {'ability': 'Armors taken by team', 'value': 80}],
                    'badge_image': 'https://cdn.r6stats.com/badges/rook_badge.png'}, {'name': 'Blitz', 'ctu': 'GSG9',
                                                                                      'role': 'Attacker', 'kills': 21,
                                                                                      'deaths': 45, 'kd': 0.4667,
                                                                                      'wins': 28, 'losses': 28, 'wl': 1,
                                                                                      'headshots': 5, 'dbnos': 15,
                                                                                      'melee_kills': 4,
                                                                                      'experience': 100850,
                                                                                      'playtime': 10911, 'abilities': [
        {'ability': 'Enemies blinded by Flash Shield', 'value': 12},
        {'ability': 'Post-flash assisted kills', 'value': 4}, {'ability': 'Post-flash follow up kills', 'value': 0}],
                                                                                      'badge_image': 'https://cdn.r6stats.com/badges/blitz_badge.png'}, {
                    'name': 'IQ', 'ctu': 'GSG9', 'role': 'Attacker', 'kills': 125, 'deaths': 171, 'kd': 0.731,
                    'wins': 96, 'losses': 111, 'wl': 0.8649, 'headshots': 53, 'dbnos': 36, 'melee_kills': 2,
                    'experience': 410083, 'playtime': 37887,
                    'abilities': [{'ability': 'Gadgets spotted', 'value': 613}],
                    'badge_image': 'https://cdn.r6stats.com/badges/iq_badge.png'}, {'name': 'Jäger', 'ctu': 'GSG9',
                                                                                    'role': 'Defender', 'kills': 455,
                                                                                    'deaths': 458, 'kd': 0.9934,
                                                                                    'wins': 359, 'losses': 287,
                                                                                    'wl': 1.2509, 'headshots': 140,
                                                                                    'dbnos': 210, 'melee_kills': 2,
                                                                                    'experience': 1226165,
                                                                                    'playtime': 121245, 'abilities': [
        {'ability': 'Gadgets destroyed by ADS', 'value': 340}],
                                                                                    'badge_image': 'https://cdn.r6stats.com/badges/jager_badge.png'}, {
                    'name': 'Bandit', 'ctu': 'GSG9', 'role': 'Defender', 'kills': 116, 'deaths': 133, 'kd': 0.8722,
                    'wins': 89, 'losses': 87, 'wl': 1.023, 'headshots': 40, 'dbnos': 39, 'melee_kills': 3,
                    'experience': 367926, 'playtime': 32308,
                    'abilities': [{'ability': 'Kills with Battery Charge', 'value': 0}],
                    'badge_image': 'https://cdn.r6stats.com/badges/bandit_badge.png'}, {'name': 'Glaz',
                                                                                        'ctu': 'Spetsnaz',
                                                                                        'role': 'Attacker', 'kills': 3,
                                                                                        'deaths': 5, 'kd': 0.6,
                                                                                        'wins': 4, 'losses': 4, 'wl': 1,
                                                                                        'headshots': 0, 'dbnos': 0,
                                                                                        'melee_kills': 0,
                                                                                        'experience': 11900,
                                                                                        'playtime': 1528, 'abilities': [
        {'ability': 'Kills with Sniper Rifle', 'value': 3},
        {'ability': 'Penetration kills with Sniper Rifle', 'value': 0}],
                                                                                        'badge_image': 'https://cdn.r6stats.com/badges/glaz_badge.png'}, {
                    'name': 'Fuze', 'ctu': 'Spetsnaz', 'role': 'Attacker', 'kills': 9, 'deaths': 12, 'kd': 0.75,
                    'wins': 5, 'losses': 9, 'wl': 0.5556, 'headshots': 4, 'dbnos': 7, 'melee_kills': 0,
                    'experience': 31370, 'playtime': 2597,
                    'abilities': [{'ability': 'Kills with Cluster Charge', 'value': 0}],
                    'badge_image': 'https://cdn.r6stats.com/badges/fuze_badge.png'}, {'name': 'Kapkan',
                                                                                      'ctu': 'Spetsnaz',
                                                                                      'role': 'Defender', 'kills': 6,
                                                                                      'deaths': 15, 'kd': 0.4,
                                                                                      'wins': 14, 'losses': 8,
                                                                                      'wl': 1.75, 'headshots': 3,
                                                                                      'dbnos': 2, 'melee_kills': 0,
                                                                                      'experience': 35980,
                                                                                      'playtime': 3888, 'abilities': [
        {'ability': 'Traps deployed', 'value': 83}, {'ability': 'Kills with Traps', 'value': 0}],
                                                                                      'badge_image': 'https://cdn.r6stats.com/badges/kapkan_badge.png'}, {
                    'name': 'Tachanka', 'ctu': 'Spetsnaz', 'role': 'Defender', 'kills': 17, 'deaths': 29, 'kd': 0.5862,
                    'wins': 16, 'losses': 20, 'wl': 0.8, 'headshots': 5, 'dbnos': 5, 'melee_kills': 0,
                    'experience': 49010, 'playtime': 6318, 'abilities': [{'ability': 'Turrets deployed', 'value': 7},
                                                                         {'ability': 'Kills with Turret', 'value': 2}],
                    'badge_image': 'https://cdn.r6stats.com/badges/tachanka_badge.png'}, {'name': 'Buck', 'ctu': 'JTF2',
                                                                                          'role': 'Attacker',
                                                                                          'kills': 159, 'deaths': 228,
                                                                                          'kd': 0.6974, 'wins': 121,
                                                                                          'losses': 156, 'wl': 0.7756,
                                                                                          'headshots': 54, 'dbnos': 67,
                                                                                          'melee_kills': 1,
                                                                                          'experience': 509935,
                                                                                          'playtime': 51747,
                                                                                          'abilities': [{
                                                                                                            'ability': 'Kills with Skeleton Key',
                                                                                                            'value': 15}],
                                                                                          'badge_image': 'https://cdn.r6stats.com/badges/buck_badge.png'}, {
                    'name': 'Frost', 'ctu': 'JTF2', 'role': 'Defender', 'kills': 10, 'deaths': 5, 'kd': 2, 'wins': 4,
                    'losses': 3, 'wl': 1.3333, 'headshots': 2, 'dbnos': 3, 'melee_kills': 1, 'experience': 18050,
                    'playtime': 1360, 'abilities': [{'ability': 'Enemies caught in Welcome Mat', 'value': 1},
                                                    {'ability': 'Enemes killed with Welcome Mat', 'value': 0}],
                    'badge_image': 'https://cdn.r6stats.com/badges/frost_badge.png'}, {'name': 'Valkyrie',
                                                                                       'ctu': 'Navy SEALs',
                                                                                       'role': 'Defender', 'kills': 57,
                                                                                       'deaths': 59, 'kd': 0.9661,
                                                                                       'wins': 37, 'losses': 42,
                                                                                       'wl': 0.881, 'headshots': 18,
                                                                                       'dbnos': 26, 'melee_kills': 0,
                                                                                       'experience': 145825,
                                                                                       'playtime': 14086, 'abilities': [
        {'ability': 'Cams deployed', 'value': 282}],
                                                                                       'badge_image': 'https://cdn.r6stats.com/badges/valkyrie_badge.png'}, {
                    'name': 'Blackbeard', 'ctu': 'Navy SEALs', 'role': 'Attacker', 'kills': 15, 'deaths': 19,
                    'kd': 0.7895, 'wins': 10, 'losses': 15, 'wl': 0.6667, 'headshots': 7, 'dbnos': 1, 'melee_kills': 0,
                    'experience': 46574, 'playtime': 4843,
                    'abilities': [{'ability': 'Damage blocked by Shield', 'value': 24}],
                    'badge_image': 'https://cdn.r6stats.com/badges/blackbeard_badge.png'}, {'name': 'Capitão',
                                                                                            'ctu': 'BOPE',
                                                                                            'role': 'Attacker',
                                                                                            'kills': 24, 'deaths': 54,
                                                                                            'kd': 0.4444, 'wins': 27,
                                                                                            'losses': 34, 'wl': 0.7941,
                                                                                            'headshots': 7, 'dbnos': 6,
                                                                                            'melee_kills': 1,
                                                                                            'experience': 74320,
                                                                                            'playtime': 8922,
                                                                                            'abilities': [{
                                                                                                              'ability': 'Kills with Lethal Dart',
                                                                                                              'value': 3},
                                                                                                          {
                                                                                                              'ability': 'Smoke Darts launched',
                                                                                                              'value': None}],
                                                                                            'badge_image': 'https://cdn.r6stats.com/badges/capitao_badge.png'}, {
                    'name': 'Caveira', 'ctu': 'BOPE', 'role': 'Defender', 'kills': 5, 'deaths': 12, 'kd': 0.4167,
                    'wins': 6, 'losses': 7, 'wl': 0.8571, 'headshots': 2, 'dbnos': 4, 'melee_kills': 0,
                    'experience': 21730, 'playtime': 2748, 'abilities': [{'ability': 'Interrogations', 'value': 2},
                                                                         {'ability': 'AI killed in Stealth',
                                                                          'value': 0}],
                    'badge_image': 'https://cdn.r6stats.com/badges/caveira_badge.png'}, {'name': 'Hibana', 'ctu': 'SAT',
                                                                                         'role': 'Attacker',
                                                                                         'kills': 133, 'deaths': 195,
                                                                                         'kd': 0.6821, 'wins': 128,
                                                                                         'losses': 132, 'wl': 0.9697,
                                                                                         'headshots': 55, 'dbnos': 49,
                                                                                         'melee_kills': 1,
                                                                                         'experience': 484652,
                                                                                         'playtime': 47961,
                                                                                         'abilities': [{
                                                                                                           'ability': 'Projectiles detonated',
                                                                                                           'value': 812}],
                                                                                         'badge_image': 'https://cdn.r6stats.com/badges/hibana_badge.png'}, {
                    'name': 'Echo', 'ctu': 'SAT', 'role': 'Defender', 'kills': 468, 'deaths': 536, 'kd': 0.8731,
                    'wins': 370, 'losses': 367, 'wl': 1.0082, 'headshots': 191, 'dbnos': 209, 'melee_kills': 5,
                    'experience': 1384420, 'playtime': 134987,
                    'abilities': [{'ability': 'Enemies hit by Drone', 'value': 177}],
                    'badge_image': 'https://cdn.r6stats.com/badges/echo_badge.png'}, {'name': 'Jackal', 'ctu': 'GEO',
                                                                                      'role': 'Attacker', 'kills': 129,
                                                                                      'deaths': 160, 'kd': 0.8063,
                                                                                      'wins': 104, 'losses': 107,
                                                                                      'wl': 0.972, 'headshots': 38,
                                                                                      'dbnos': 43, 'melee_kills': 0,
                                                                                      'experience': 412305,
                                                                                      'playtime': 37394, 'abilities': [
        {'ability': 'Cazador kill assists', 'value': 19}],
                                                                                      'badge_image': 'https://cdn.r6stats.com/badges/jackal_badge.png'}, {
                    'name': 'Mira', 'ctu': 'GEO', 'role': 'Defender', 'kills': 28, 'deaths': 26, 'kd': 1.0769,
                    'wins': 16, 'losses': 21, 'wl': 0.7619, 'headshots': 13, 'dbnos': 10, 'melee_kills': 0,
                    'experience': 86570, 'playtime': 7710,
                    'abilities': [{'ability': 'Black Mirrors deployed', 'value': 71}],
                    'badge_image': 'https://cdn.r6stats.com/badges/mira_badge.png'}, {'name': 'Ying', 'ctu': 'SDU',
                                                                                      'role': 'Attacker', 'kills': 59,
                                                                                      'deaths': 66, 'kd': 0.8939,
                                                                                      'wins': 44, 'losses': 44, 'wl': 1,
                                                                                      'headshots': 22, 'dbnos': 20,
                                                                                      'melee_kills': 3,
                                                                                      'experience': 194455,
                                                                                      'playtime': 15846, 'abilities': [
        {'ability': 'Candelas detonated', 'value': 110}],
                                                                                      'badge_image': 'https://cdn.r6stats.com/badges/ying_badge.png'}, {
                    'name': 'Lesion', 'ctu': 'SDU', 'role': 'Defender', 'kills': 66, 'deaths': 69, 'kd': 0.9565,
                    'wins': 52, 'losses': 47, 'wl': 1.1064, 'headshots': 20, 'dbnos': 34, 'melee_kills': 1,
                    'experience': 225980, 'playtime': 19211,
                    'abilities': [{'ability': 'Enemies hit by Gu Mine', 'value': 112}],
                    'badge_image': 'https://cdn.r6stats.com/badges/lesion_badge.png'}, {'name': 'Zofia', 'ctu': 'GROM',
                                                                                        'role': 'Attacker',
                                                                                        'kills': 181, 'deaths': 193,
                                                                                        'kd': 0.9378, 'wins': 134,
                                                                                        'losses': 137, 'wl': 0.9781,
                                                                                        'headshots': 71, 'dbnos': 68,
                                                                                        'melee_kills': 0,
                                                                                        'experience': 554695,
                                                                                        'playtime': 49836,
                                                                                        'abilities': [{
                                                                                                          'ability': 'Concussion Grenades detonated',
                                                                                                          'value': 169}],
                                                                                        'badge_image': 'https://cdn.r6stats.com/badges/zofia_badge.png'}, {
                    'name': 'Ela', 'ctu': 'GROM', 'role': 'Defender', 'kills': 235, 'deaths': 268, 'kd': 0.8769,
                    'wins': 181, 'losses': 169, 'wl': 1.071, 'headshots': 94, 'dbnos': 110, 'melee_kills': 7,
                    'experience': 711275, 'playtime': 63256,
                    'abilities': [{'ability': 'Enemies hit by Grzmot Mine', 'value': 397}],
                    'badge_image': 'https://cdn.r6stats.com/badges/ela_badge.png'}, {'name': 'Dokkaebi',
                                                                                     'ctu': '707th SMB',
                                                                                     'role': 'Attacker', 'kills': 6,
                                                                                     'deaths': 4, 'kd': 1.5, 'wins': 3,
                                                                                     'losses': 4, 'wl': 0.75,
                                                                                     'headshots': 0, 'dbnos': 0,
                                                                                     'melee_kills': 0,
                                                                                     'experience': 11145,
                                                                                     'playtime': 984, 'abilities': [
        {'ability': 'Phones hacked', 'value': 3}],
                                                                                     'badge_image': 'https://cdn.r6stats.com/badges/dokkaebi_badge.png'}, {
                    'name': 'Vigil', 'ctu': '707th SMB', 'role': 'Defender', 'kills': 217, 'deaths': 198, 'kd': 1.096,
                    'wins': 174, 'losses': 123, 'wl': 1.4146, 'headshots': 63, 'dbnos': 79, 'melee_kills': 2,
                    'experience': 609021, 'playtime': 54002,
                    'abilities': [{'ability': 'Drones deceived', 'value': 387}],
                    'badge_image': 'https://cdn.r6stats.com/badges/vigil_badge.png'}, {'name': 'Lion', 'ctu': 'CBRN',
                                                                                       'role': 'Attacker', 'kills': 26,
                                                                                       'deaths': 45, 'kd': 0.5778,
                                                                                       'wins': 23, 'losses': 33,
                                                                                       'wl': 0.697, 'headshots': 12,
                                                                                       'dbnos': 8, 'melee_kills': 0,
                                                                                       'experience': 104700,
                                                                                       'playtime': 9979, 'abilities': [
        {'ability': 'Enemies marked by Drone', 'value': 12}],
                                                                                       'badge_image': 'https://cdn.r6stats.com/badges/lion_badge.png'}, {
                    'name': 'Finka', 'ctu': 'CBRN', 'role': 'Attacker', 'kills': 16, 'deaths': 17, 'kd': 0.9412,
                    'wins': 9, 'losses': 13, 'wl': 0.6923, 'headshots': 5, 'dbnos': 6, 'melee_kills': 0,
                    'experience': 42765, 'playtime': 4007,
                    'abilities': [{'ability': 'Adrenaline Surges used', 'value': 37}],
                    'badge_image': 'https://cdn.r6stats.com/badges/finka_badge.png'}, {'name': 'Alibi', 'ctu': 'GIS',
                                                                                       'role': 'Defender', 'kills': 108,
                                                                                       'deaths': 91, 'kd': 1.1868,
                                                                                       'wins': 70, 'losses': 62,
                                                                                       'wl': 1.129, 'headshots': 46,
                                                                                       'dbnos': 55, 'melee_kills': 3,
                                                                                       'experience': 308665,
                                                                                       'playtime': 24221, 'abilities': [
        {'ability': 'Enemies tricked by Prisma', 'value': 126}],
                                                                                       'badge_image': 'https://cdn.r6stats.com/badges/alibi_badge.png'}, {
                    'name': 'Maestro', 'ctu': 'GIS', 'role': 'Defender', 'kills': 193, 'deaths': 200, 'kd': 0.965,
                    'wins': 166, 'losses': 140, 'wl': 1.1857, 'headshots': 68, 'dbnos': 78, 'melee_kills': 0,
                    'experience': 590955, 'playtime': 59568,
                    'abilities': [{'ability': 'Kills with Evil Eye', 'value': 9}],
                    'badge_image': 'https://cdn.r6stats.com/badges/maestro_badge.png'}, {'name': 'Maverick',
                                                                                         'ctu': 'GSUTR',
                                                                                         'role': 'Attacker',
                                                                                         'kills': 40, 'deaths': 62,
                                                                                         'kd': 0.6452, 'wins': 34,
                                                                                         'losses': 41, 'wl': 0.8293,
                                                                                         'headshots': 13, 'dbnos': 11,
                                                                                         'melee_kills': 3,
                                                                                         'experience': 110647,
                                                                                         'playtime': 11906,
                                                                                         'abilities': [{
                                                                                                           'ability': 'Walls breached with Torch',
                                                                                                           'value': 97}],
                                                                                         'badge_image': 'https://cdn.r6stats.com/badges/maverick_badge.png'}, {
                    'name': 'Clash', 'ctu': 'GSUTR', 'role': 'Defender', 'kills': 9, 'deaths': 37, 'kd': 0.2432,
                    'wins': 31, 'losses': 28, 'wl': 1.1071, 'headshots': 2, 'dbnos': 5, 'melee_kills': 1,
                    'experience': 119070, 'playtime': 10870,
                    'abilities': [{'ability': 'Bullets stopped by CCE Shield', 'value': None},
                                  {'ability': 'Enemies killed whilst slowed down by CCE Shield', 'value': 13}],
                    'badge_image': 'https://cdn.r6stats.com/badges/clash_badge.png'}, {'name': 'SAS Recruit',
                                                                                       'ctu': 'SAS', 'role': 'Recruit',
                                                                                       'kills': 0, 'deaths': 5, 'kd': 0,
                                                                                       'wins': 3, 'losses': 3, 'wl': 1,
                                                                                       'headshots': 0, 'dbnos': 0,
                                                                                       'melee_kills': 0,
                                                                                       'experience': 4360,
                                                                                       'playtime': 1117}, {
                    'name': 'FBI Recruit', 'ctu': 'FBI SWAT', 'role': 'Recruit', 'kills': 12, 'deaths': 21,
                    'kd': 0.5714, 'wins': 10, 'losses': 13, 'wl': 0.7692, 'headshots': 4, 'dbnos': 4, 'melee_kills': 1,
                    'experience': 39750, 'playtime': 3947}, {'name': 'GSG-9 Recruit', 'ctu': 'GSG9', 'role': 'Recruit',
                                                             'kills': 2, 'deaths': 5, 'kd': 0.4, 'wins': 2, 'losses': 2,
                                                             'wl': 1, 'headshots': 0, 'dbnos': 1, 'melee_kills': 0,
                                                             'experience': 2850, 'playtime': 707}, {'name': 'Kaid',
                                                                                                    'ctu': 'GIGR',
                                                                                                    'role': 'Defender',
                                                                                                    'kills': 7,
                                                                                                    'deaths': 10,
                                                                                                    'kd': 0.7,
                                                                                                    'wins': 8,
                                                                                                    'losses': 7,
                                                                                                    'wl': 1.1429,
                                                                                                    'headshots': 3,
                                                                                                    'dbnos': 3,
                                                                                                    'melee_kills': 0,
                                                                                                    'experience': 29140,
                                                                                                    'playtime': 2904,
                                                                                                    'abilities': [{
                                                                                                                      'ability': 'Electroclaw electrifies',
                                                                                                                      'value': 32}],
                                                                                                    'badge_image': 'https://cdn.r6stats.com/badges/kaid_badge.png'}, {
                    'name': 'Nomad', 'ctu': 'GIGR', 'role': 'Attacker', 'kills': 41, 'deaths': 75, 'kd': 0.5467,
                    'wins': 48, 'losses': 52, 'wl': 0.9231, 'headshots': 19, 'dbnos': 10, 'melee_kills': 0,
                    'experience': 174945, 'playtime': 18299,
                    'abilities': [{'ability': 'Airjabs detonated', 'value': 41}],
                    'badge_image': 'https://cdn.r6stats.com/badges/nomad_badge.png'}, {'name': 'Gridlock',
                                                                                       'ctu': 'SASR',
                                                                                       'role': 'Attacker', 'kills': 73,
                                                                                       'deaths': 85, 'kd': 0.8588,
                                                                                       'wins': 62, 'losses': 54,
                                                                                       'wl': 1.1481, 'headshots': 34,
                                                                                       'dbnos': 32, 'melee_kills': 1,
                                                                                       'experience': 271045,
                                                                                       'playtime': 21397, 'abilities': [
        {'ability': 'Trax deployed', 'value': 183}],
                                                                                       'badge_image': 'https://cdn.r6stats.com/badges/gridlock_badge.png'}, {
                    'name': 'Mozzie', 'ctu': 'SASR', 'role': 'Defender', 'kills': 323, 'deaths': 284, 'kd': 1.1373,
                    'wins': 217, 'losses': 201, 'wl': 1.0796, 'headshots': 129, 'dbnos': 127, 'melee_kills': 1,
                    'experience': 899425, 'playtime': 78058, 'abilities': [{'ability': 'Drones hacked', 'value': 319}],
                    'badge_image': 'https://cdn.r6stats.com/badges/mozzie_badge.png'}, {'name': 'Nøkk',
                                                                                        'ctu': 'Jaeger Corps',
                                                                                        'role': 'Attacker', 'kills': 71,
                                                                                        'deaths': 85, 'kd': 0.8353,
                                                                                        'wins': 60, 'losses': 55,
                                                                                        'wl': 1.0909, 'headshots': 23,
                                                                                        'dbnos': 35, 'melee_kills': 1,
                                                                                        'experience': 240526,
                                                                                        'playtime': 19425,
                                                                                        'abilities': [{
                                                                                                          'ability': 'Observation tools deceived',
                                                                                                          'value': 36}],
                                                                                        'badge_image': 'https://cdn.r6stats.com/badges/nokk_badge.png'}, {
                    'name': 'Warden', 'ctu': 'Secret Service', 'role': 'Defender', 'kills': 2, 'deaths': 2, 'kd': 1,
                    'wins': 1, 'losses': 1, 'wl': 1, 'headshots': 1, 'dbnos': 1, 'melee_kills': 0, 'experience': 1115,
                    'playtime': 416, 'abilities': [{'ability': 'Kills whilst Glance active', 'value': 0}],
                    'badge_image': 'https://cdn.r6stats.com/badges/warden_badge.png'}, {'name': 'Amaru', 'ctu': 'APCA',
                                                                                        'role': 'Attacker', 'kills': 9,
                                                                                        'deaths': 6, 'kd': 1.5,
                                                                                        'wins': 6, 'losses': 3, 'wl': 2,
                                                                                        'headshots': 6, 'dbnos': 2,
                                                                                        'melee_kills': 0,
                                                                                        'experience': 24010,
                                                                                        'playtime': 1363, 'abilities': [
        {'ability': 'Distance Reeled with Garra Hook', 'value': 66}],
                                                                                        'badge_image': 'https://cdn.r6stats.com/badges/amaru_badge.png'}, {
                    'name': 'Goyo', 'ctu': 'Feurzas Especiales', 'role': 'Defender', 'kills': 29, 'deaths': 35,
                    'kd': 0.8286, 'wins': 19, 'losses': 26, 'wl': 0.7308, 'headshots': 13, 'dbnos': 13,
                    'melee_kills': 0, 'experience': 92245, 'playtime': 8421,
                    'abilities': [{'ability': 'Volcan Shield detonations', 'value': 41}],
                    'badge_image': 'https://cdn.r6stats.com/badges/goyo_badge.png'}, {'name': 'Kali',
                                                                                      'ctu': 'Nighthaven',
                                                                                      'role': 'Attacker', 'kills': 28,
                                                                                      'deaths': 45, 'kd': 0.6222,
                                                                                      'wins': 22, 'losses': 36,
                                                                                      'wl': 0.6111, 'headshots': 11,
                                                                                      'dbnos': 15, 'melee_kills': 0,
                                                                                      'experience': 85400,
                                                                                      'playtime': 10648, 'abilities': [
        {'ability': 'Gadgets destroyed by Explosive Lance', 'value': 10}],
                                                                                      'badge_image': 'https://cdn.r6stats.com/badges/kali_badge.png'}, {
                    'name': 'Wamai', 'ctu': 'Nighthaven', 'role': 'Defender', 'kills': 43, 'deaths': 52, 'kd': 0.8269,
                    'wins': 41, 'losses': 35, 'wl': 1.1714, 'headshots': 13, 'dbnos': 16, 'melee_kills': 0,
                    'experience': 126310, 'playtime': 13129,
                    'abilities': [{'ability': 'Gadgets destroyed by Mag-Net', 'value': 31}],
                    'badge_image': 'https://cdn.r6stats.com/badges/wamai_badge.png'}, {'name': 'Oryx', 'ctu': 'GIGR',
                                                                                       'role': 'Defender', 'kills': 71,
                                                                                       'deaths': 61, 'kd': 1.1639,
                                                                                       'wins': 47, 'losses': 40,
                                                                                       'wl': 1.175, 'headshots': 28,
                                                                                       'dbnos': 26, 'melee_kills': 4,
                                                                                       'experience': 178805,
                                                                                       'playtime': 15842, 'abilities': [
        {'ability': 'Kills after Dash activated', 'value': 15}],
                                                                                       'badge_image': 'https://cdn.r6stats.com/badges/oryx_badge.png'}, {
                    'name': 'Iana', 'ctu': 'REU', 'role': 'Attacker', 'kills': 1, 'deaths': 3, 'kd': 0.3333, 'wins': 3,
                    'losses': 2, 'wl': 1.5, 'headshots': 1, 'dbnos': 0, 'melee_kills': 0, 'experience': 8600,
                    'playtime': 894, 'abilities': [{'ability': 'Kills after Replicator activated', 'value': 0}],
                    'badge_image': 'https://cdn.r6stats.com/badges/iana_badge.png'}, {'name': 'Ace',
                                                                                      'ctu': 'Nighthaven',
                                                                                      'role': 'Attacker', 'kills': 700,
                                                                                      'deaths': 666, 'kd': 1.0511,
                                                                                      'wins': 487, 'losses': 462,
                                                                                      'wl': 1.0541, 'headshots': 269,
                                                                                      'dbnos': 249, 'melee_kills': 7,
                                                                                      'experience': 2004246,
                                                                                      'playtime': 171455, 'abilities': [
        {'ability': 'S.E.L.M.A detonations', 'value': 1417}],
                                                                                      'badge_image': 'https://cdn.r6stats.com/badges/ace_badge.png'}, {
                    'name': 'Melusi', 'ctu': 'ITF', 'role': 'Defender', 'kills': 47, 'deaths': 59, 'kd': 0.7966,
                    'wins': 47, 'losses': 38, 'wl': 1.2368, 'headshots': 10, 'dbnos': 26, 'melee_kills': 1,
                    'experience': 151980, 'playtime': 16330,
                    'abilities': [{'ability': 'Attackers slowed by Banshee', 'value': 115}],
                    'badge_image': 'https://cdn.r6stats.com/badges/melusi_badge.png'}, {'name': 'Zero',
                                                                                        'ctu': 'Navy SEALs',
                                                                                        'role': 'Attacker',
                                                                                        'kills': 132, 'deaths': 156,
                                                                                        'kd': 0.8462, 'wins': 111,
                                                                                        'losses': 108, 'wl': 1.0278,
                                                                                        'headshots': 46, 'dbnos': 52,
                                                                                        'melee_kills': 1,
                                                                                        'experience': 424150,
                                                                                        'playtime': 41825,
                                                                                        'abilities': [{
                                                                                                          'ability': 'Gadgets destroyed by Argus Camera',
                                                                                                          'value': 14}],
                                                                                        'badge_image': 'https://cdn.r6stats.com/badges/zero_badge.png'}, {
                    'name': 'Aruni', 'ctu': 'Nighthaven', 'role': 'Defender', 'kills': 78, 'deaths': 84, 'kd': 0.9286,
                    'wins': 58, 'losses': 58, 'wl': 1, 'headshots': 37, 'dbnos': 30, 'melee_kills': 1,
                    'experience': 200295, 'playtime': 22144,
                    'badge_image': 'https://cdn.r6stats.com/badges/aruni_badge.png'}, {'name': 'Flores',
                                                                                       'ctu': 'Unaffiliated',
                                                                                       'role': 'Attacker', 'kills': 16,
                                                                                       'deaths': 31, 'kd': 0.5161,
                                                                                       'wins': 19, 'losses': 24,
                                                                                       'wl': 0.7917, 'headshots': 4,
                                                                                       'dbnos': 6, 'melee_kills': 0,
                                                                                       'experience': 64630,
                                                                                       'playtime': 7692,
                                                                                       'badge_image': 'https://cdn.r6stats.com/badges/flores_badge.png'}]
