weaponDataExample = {
    'weapon': 'L85A2',
    'category': 'Assault Rifle',
    'kills': 151,
    'deaths': 246,
    'kd': 0.6138,
    'headshots': 58,
    'headshot_percentage': 38.41,
    'times_chosen': 49,
    'bullets_fired': 0,
    'bullets_hit': 1160,
    'created': '2020-06-20T13:09:00.000Z',
    'last_updated': '2021-05-09T12:28:02.000Z'
}, {'weapon': 'AR33', 'category': 'Assault Rifle', 'kills': 91, 'deaths': 52, 'kd': 1.75, 'headshots': 34,
    'headshot_percentage': 37.36, 'times_chosen': 212, 'bullets_fired': 0, 'bullets_hit': 969,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'G36C',
                                                                                         'category': 'Assault Rifle',
                                                                                         'kills': 20, 'deaths': 54,
                                                                                         'kd': 0.3704, 'headshots': 11,
                                                                                         'headshot_percentage': 55.00000000000001,
                                                                                         'times_chosen': 33,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 161,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': '416-C CARBINE', 'category': 'Assault Rifle', 'kills': 466, 'deaths': 310, 'kd': 1.5032, 'headshots': 142,
    'headshot_percentage': 30.470000000000002, 'times_chosen': 75, 'bullets_fired': 0, 'bullets_hit': 3799,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'R4-C',
                                                                                         'category': 'Assault Rifle',
                                                                                         'kills': 136, 'deaths': 350,
                                                                                         'kd': 0.3886, 'headshots': 47,
                                                                                         'headshot_percentage': 34.56,
                                                                                         'times_chosen': 28,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 1349,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': '556XI', 'category': 'Assault Rifle', 'kills': 21, 'deaths': 170, 'kd': 0.1235, 'headshots': 6,
    'headshot_percentage': 28.57, 'times_chosen': 39, 'bullets_fired': 0, 'bullets_hit': 246,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'F2',
                                                                                         'category': 'Assault Rifle',
                                                                                         'kills': 274, 'deaths': 112,
                                                                                         'kd': 2.4464, 'headshots': 134,
                                                                                         'headshot_percentage': 48.91,
                                                                                         'times_chosen': 78,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 2188,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'AK-12', 'category': 'Assault Rifle', 'kills': 755, 'deaths': 247, 'kd': 3.0567, 'headshots': 286,
    'headshot_percentage': 37.88, 'times_chosen': 2, 'bullets_fired': 0, 'bullets_hit': 5448,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'AUG A2',
                                                                                         'category': 'Assault Rifle',
                                                                                         'kills': 47, 'deaths': 50,
                                                                                         'kd': 0.94, 'headshots': 13,
                                                                                         'headshot_percentage': 27.66,
                                                                                         'times_chosen': 19,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 391,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': '552 Commando', 'category': 'Assault Rifle', 'kills': 17, 'deaths': 90, 'kd': 0.1889, 'headshots': 7,
    'headshot_percentage': 41.18, 'times_chosen': 37, 'bullets_fired': 0, 'bullets_hit': 113,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'C8-SFW',
                                                                                         'category': 'Assault Rifle',
                                                                                         'kills': 166, 'deaths': 121,
                                                                                         'kd': 1.3719, 'headshots': 62,
                                                                                         'headshot_percentage': 37.35,
                                                                                         'times_chosen': 146,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 1336,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'MK17 CQB', 'category': 'Assault Rifle', 'kills': 17, 'deaths': 71, 'kd': 0.2394, 'headshots': 8,
    'headshot_percentage': 47.06, 'times_chosen': 13, 'bullets_fired': 0, 'bullets_hit': 120,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'PARA-308',
                                                                                         'category': 'Assault Rifle',
                                                                                         'kills': 12, 'deaths': 48,
                                                                                         'kd': 0.25, 'headshots': 7,
                                                                                         'headshot_percentage': 58.330000000000005,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 84,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'Type-89', 'category': 'Assault Rifle', 'kills': 120, 'deaths': 136, 'kd': 0.8824, 'headshots': 54,
    'headshot_percentage': 45, 'times_chosen': 113, 'bullets_fired': 0, 'bullets_hit': 1112,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': '417',
                                                                                         'category': 'Marksman Rifle',
                                                                                         'kills': 1, 'deaths': 24,
                                                                                         'kd': 0.0417, 'headshots': 0,
                                                                                         'headshot_percentage': 0,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 5,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'C7E', 'category': 'Assault Rifle', 'kills': 135, 'deaths': 140, 'kd': 0.9643, 'headshots': 44,
    'headshot_percentage': 32.59, 'times_chosen': 0, 'bullets_fired': 0, 'bullets_hit': 1133,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'v308',
                                                                                         'category': 'Assault Rifle',
                                                                                         'kills': 27, 'deaths': 45,
                                                                                         'kd': 0.6, 'headshots': 12,
                                                                                         'headshot_percentage': 44.440000000000005,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 255,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'M762', 'category': 'Assault Rifle', 'kills': 191, 'deaths': 223, 'kd': 0.8565, 'headshots': 78,
    'headshot_percentage': 40.839999999999996, 'times_chosen': 0, 'bullets_fired': 0, 'bullets_hit': 1450,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'AR-15.50',
                                                                                         'category': 'Assault Rifle',
                                                                                         'kills': 0, 'deaths': 6,
                                                                                         'kd': 0, 'headshots': 0,
                                                                                         'headshot_percentage': 0,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 0,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'M4', 'category': 'Assault Rifle', 'kills': 25, 'deaths': 86, 'kd': 0.2907, 'headshots': 11,
    'headshot_percentage': 44, 'times_chosen': 0, 'bullets_fired': 0, 'bullets_hit': 202,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'PDW9',
                                                                                         'category': 'Submachine Gun',
                                                                                         'kills': 0, 'deaths': 45,
                                                                                         'kd': 0, 'headshots': 0,
                                                                                         'headshot_percentage': 0,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 0,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'Vector .45 ACP', 'category': 'Submachine Gun', 'kills': 42, 'deaths': 100, 'kd': 0.42, 'headshots': 24,
    'headshot_percentage': 57.14, 'times_chosen': 11, 'bullets_fired': 0, 'bullets_hit': 492,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'MP5SD',
                                                                                         'category': 'Submachine Gun',
                                                                                         'kills': 409, 'deaths': 60,
                                                                                         'kd': 6.8167, 'headshots': 182,
                                                                                         'headshot_percentage': 44.5,
                                                                                         'times_chosen': 96,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 3633,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'M12', 'category': 'Submachine Gun', 'kills': 3, 'deaths': 68, 'kd': 0.0441, 'headshots': 2,
    'headshot_percentage': 66.67, 'times_chosen': 0, 'bullets_fired': 0, 'bullets_hit': 25,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'MPX',
                                                                                         'category': 'Submachine Gun',
                                                                                         'kills': 110, 'deaths': 232,
                                                                                         'kd': 0.4741, 'headshots': 42,
                                                                                         'headshot_percentage': 38.18,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 1168,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': '9mm C1', 'category': 'Submachine Gun', 'kills': 16, 'deaths': 142, 'kd': 0.1127, 'headshots': 2,
    'headshot_percentage': 12.5, 'times_chosen': 0, 'bullets_fired': 0, 'bullets_hit': 102,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'MP7',
                                                                                         'category': 'Submachine Gun',
                                                                                         'kills': 95, 'deaths': 204,
                                                                                         'kd': 0.4657, 'headshots': 40,
                                                                                         'headshot_percentage': 42.11,
                                                                                         'times_chosen': 72,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 966,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': '9x19VSN', 'category': 'Submachine Gun', 'kills': 7, 'deaths': 156, 'kd': 0.0449, 'headshots': 3,
    'headshot_percentage': 42.86, 'times_chosen': 11, 'bullets_fired': 0, 'bullets_hit': 98,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'MP5',
                                                                                         'category': 'Submachine Gun',
                                                                                         'kills': 208, 'deaths': 382,
                                                                                         'kd': 0.5445, 'headshots': 85,
                                                                                         'headshot_percentage': 40.87,
                                                                                         'times_chosen': 52,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 2174,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'P90', 'category': 'Submachine Gun', 'kills': 0, 'deaths': 31, 'kd': 0, 'headshots': 0,
    'headshot_percentage': 0, 'times_chosen': 0, 'bullets_fired': 0, 'bullets_hit': 0,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'UMP45',
                                                                                         'category': 'Submachine Gun',
                                                                                         'kills': 16, 'deaths': 129,
                                                                                         'kd': 0.124, 'headshots': 6,
                                                                                         'headshot_percentage': 37.5,
                                                                                         'times_chosen': 36,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 163,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'FMG-9', 'category': 'Submachine Gun', 'kills': 81, 'deaths': 146, 'kd': 0.5548, 'headshots': 29,
    'headshot_percentage': 35.8, 'times_chosen': 63, 'bullets_fired': 0, 'bullets_hit': 741,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'MP5K',
                                                                                         'category': 'Submachine Gun',
                                                                                         'kills': 23, 'deaths': 110,
                                                                                         'kd': 0.2091, 'headshots': 12,
                                                                                         'headshot_percentage': 52.17,
                                                                                         'times_chosen': 33,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 214,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'SMG-12', 'category': 'Machine Pistol', 'kills': 13, 'deaths': 28, 'kd': 0.4643, 'headshots': 6,
    'headshot_percentage': 46.150000000000006, 'times_chosen': 0, 'bullets_fired': 0, 'bullets_hit': 222,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'K1A',
                                                                                         'category': 'Submachine Gun',
                                                                                         'kills': 206, 'deaths': 217,
                                                                                         'kd': 0.9493, 'headshots': 61,
                                                                                         'headshot_percentage': 29.609999999999996,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 1597,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'C75 Auto', 'category': 'Machine Pistol', 'kills': 1, 'deaths': 22, 'kd': 0.0455, 'headshots': 1,
    'headshot_percentage': 100, 'times_chosen': 2, 'bullets_fired': 0, 'bullets_hit': 10,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'Mx4 Storm',
                                                                                         'category': 'Submachine Gun',
                                                                                         'kills': 96, 'deaths': 89,
                                                                                         'kd': 1.0787, 'headshots': 45,
                                                                                         'headshot_percentage': 46.88,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 904,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'T-5 SMG', 'category': 'Submachine Gun', 'kills': 113, 'deaths': 262, 'kd': 0.4313, 'headshots': 37,
    'headshot_percentage': 32.74, 'times_chosen': 69, 'bullets_fired': 0, 'bullets_hit': 1155,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'Scorpion EVO 3 A1',
                                                                                         'category': 'Submachine Gun',
                                                                                         'kills': 199, 'deaths': 114,
                                                                                         'kd': 1.7456, 'headshots': 85,
                                                                                         'headshot_percentage': 42.71,
                                                                                         'times_chosen': 59,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 2275,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': '6P41', 'category': 'Light Machine Gun', 'kills': 0, 'deaths': 48, 'kd': 0, 'headshots': 0,
    'headshot_percentage': 0, 'times_chosen': 1, 'bullets_fired': 0, 'bullets_hit': 0,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'G8A1',
                                                                                         'category': 'Light Machine Gun',
                                                                                         'kills': 116, 'deaths': 139,
                                                                                         'kd': 0.8345, 'headshots': 52,
                                                                                         'headshot_percentage': 44.83,
                                                                                         'times_chosen': 58,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 1108,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'M249', 'category': 'Light Machine Gun', 'kills': 5, 'deaths': 29, 'kd': 0.1724, 'headshots': 1,
    'headshot_percentage': 20, 'times_chosen': 0, 'bullets_fired': 0, 'bullets_hit': 41,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'ALDA 5.56',
                                                                                         'category': 'Light Machine Gun',
                                                                                         'kills': 175, 'deaths': 58,
                                                                                         'kd': 3.0172, 'headshots': 68,
                                                                                         'headshot_percentage': 38.86,
                                                                                         'times_chosen': 237,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 1412,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'T-95 LSW', 'category': 'Light Machine Gun', 'kills': 55, 'deaths': 69, 'kd': 0.7971, 'headshots': 22,
    'headshot_percentage': 40, 'times_chosen': 0, 'bullets_fired': 0, 'bullets_hit': 431,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'LMG-E',
                                                                                         'category': 'Light Machine Gun',
                                                                                         'kills': 0, 'deaths': 30,
                                                                                         'kd': 0, 'headshots': 0,
                                                                                         'headshot_percentage': 0,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 4,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'SR-25', 'category': 'Marksman Rifle', 'kills': 0, 'deaths': 16, 'kd': 0, 'headshots': 0,
    'headshot_percentage': 0, 'times_chosen': 0, 'bullets_fired': 0, 'bullets_hit': 0,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'CAMRS',
                                                                                         'category': 'Marksman Rifle',
                                                                                         'kills': 2, 'deaths': 10,
                                                                                         'kd': 0.2, 'headshots': 1,
                                                                                         'headshot_percentage': 50,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 6,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'OTs-03', 'category': 'Marksman Rifle', 'kills': 3, 'deaths': 57, 'kd': 0.0526, 'headshots': 0,
    'headshot_percentage': 0, 'times_chosen': 4, 'bullets_fired': 0, 'bullets_hit': 19,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'Mk 14 EBR',
                                                                                         'category': 'Marksman Rifle',
                                                                                         'kills': 2, 'deaths': 64,
                                                                                         'kd': 0.0313, 'headshots': 0,
                                                                                         'headshot_percentage': 0,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 5,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'P229', 'category': 'Handgun', 'kills': 16, 'deaths': 5, 'kd': 3.2, 'headshots': 6,
    'headshot_percentage': 37.5, 'times_chosen': 4, 'bullets_fired': 0, 'bullets_hit': 93,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'P226 MK 25',
                                                                                         'category': 'Handgun',
                                                                                         'kills': 8, 'deaths': 14,
                                                                                         'kd': 0.5714, 'headshots': 0,
                                                                                         'headshot_percentage': 0,
                                                                                         'times_chosen': 242,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 76,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'M45 MEUSOC', 'category': 'Handgun', 'kills': 7, 'deaths': 14, 'kd': 0.5, 'headshots': 1,
    'headshot_percentage': 14.29, 'times_chosen': 134, 'bullets_fired': 0, 'bullets_hit': 93,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': '5.7 USG',
                                                                                         'category': 'Handgun',
                                                                                         'kills': 5, 'deaths': 16,
                                                                                         'kd': 0.3125, 'headshots': 0,
                                                                                         'headshot_percentage': 0,
                                                                                         'times_chosen': 2,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 137,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'P9', 'category': 'Handgun', 'kills': 39, 'deaths': 53, 'kd': 0.7358, 'headshots': 6,
    'headshot_percentage': 15.379999999999999, 'times_chosen': 137, 'bullets_fired': 0, 'bullets_hit': 552,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'LFP586',
                                                                                         'category': 'Handgun',
                                                                                         'kills': 0, 'deaths': 14,
                                                                                         'kd': 0, 'headshots': 0,
                                                                                         'headshot_percentage': 0,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 8,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'PMM', 'category': 'Handgun', 'kills': 5, 'deaths': 13, 'kd': 0.3846, 'headshots': 2,
    'headshot_percentage': 40, 'times_chosen': 20, 'bullets_fired': 0, 'bullets_hit': 28,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'GSH-18',
                                                                                         'category': 'Handgun',
                                                                                         'kills': 1, 'deaths': 8,
                                                                                         'kd': 0.125, 'headshots': 0,
                                                                                         'headshot_percentage': 0,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 4,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'P12', 'category': 'Handgun', 'kills': 37, 'deaths': 86, 'kd': 0.4302, 'headshots': 12,
    'headshot_percentage': 32.43, 'times_chosen': 293, 'bullets_fired': 0, 'bullets_hit': 458,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'MK1 9mm',
                                                                                         'category': 'Handgun',
                                                                                         'kills': 2, 'deaths': 10,
                                                                                         'kd': 0.2, 'headshots': 0,
                                                                                         'headshot_percentage': 0,
                                                                                         'times_chosen': 160,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 87,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'D-50', 'category': 'Handgun', 'kills': 62, 'deaths': 83, 'kd': 0.747, 'headshots': 4,
    'headshot_percentage': 6.45, 'times_chosen': 16, 'bullets_fired': 0, 'bullets_hit': 148,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'PRB92',
                                                                                         'category': 'Handgun',
                                                                                         'kills': 6, 'deaths': 70,
                                                                                         'kd': 0.0857, 'headshots': 0,
                                                                                         'headshot_percentage': 0,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 56,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'USP40', 'category': 'Handgun', 'kills': 0, 'deaths': 2, 'kd': 0, 'headshots': 0,
    'headshot_percentage': 0, 'times_chosen': 0, 'bullets_fired': 0, 'bullets_hit': 0,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'Bailiff 410',
                                                                                         'category': 'Handgun',
                                                                                         'kills': 10, 'deaths': 3,
                                                                                         'kd': 3.3333, 'headshots': 0,
                                                                                         'headshot_percentage': 0,
                                                                                         'times_chosen': 145,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 161,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'Keratos .357', 'category': 'Handgun', 'kills': 3, 'deaths': 11, 'kd': 0.2727, 'headshots': 1,
    'headshot_percentage': 33.33, 'times_chosen': 93, 'bullets_fired': 0, 'bullets_hit': 20,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'Q-929',
                                                                                         'category': 'Handgun',
                                                                                         'kills': 3, 'deaths': 21,
                                                                                         'kd': 0.1429, 'headshots': 1,
                                                                                         'headshot_percentage': 33.33,
                                                                                         'times_chosen': 69,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 35,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'RG15', 'category': 'Handgun', 'kills': 30, 'deaths': 38, 'kd': 0.7895, 'headshots': 9,
    'headshot_percentage': 30, 'times_chosen': 59, 'bullets_fired': 0, 'bullets_hit': 305,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'P-10C',
                                                                                         'category': 'Handgun',
                                                                                         'kills': 0, 'deaths': 6,
                                                                                         'kd': 0, 'headshots': 0,
                                                                                         'headshot_percentage': 0,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 0,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'ITA12L', 'category': 'Shotgun', 'kills': 1, 'deaths': 3, 'kd': 0.3333, 'headshots': 0,
    'headshot_percentage': 0, 'times_chosen': 0, 'bullets_fired': 0, 'bullets_hit': 2,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'ITA12S',
                                                                                         'category': 'Shotgun',
                                                                                         'kills': 5, 'deaths': 11,
                                                                                         'kd': 0.4545, 'headshots': 0,
                                                                                         'headshot_percentage': 0,
                                                                                         'times_chosen': 11,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 18,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'Super 90', 'category': 'Shotgun', 'kills': 0, 'deaths': 10, 'kd': 0, 'headshots': 0,
    'headshot_percentage': 0, 'times_chosen': 0, 'bullets_fired': 0, 'bullets_hit': 0,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'SPAS-12',
                                                                                         'category': 'Shotgun',
                                                                                         'kills': 0, 'deaths': 10,
                                                                                         'kd': 0, 'headshots': 0,
                                                                                         'headshot_percentage': 0,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 1,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'SPAS-15', 'category': 'Shotgun', 'kills': 2, 'deaths': 20, 'kd': 0.1, 'headshots': 0,
    'headshot_percentage': 0, 'times_chosen': 0, 'bullets_fired': 0, 'bullets_hit': 13,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'Supernova',
                                                                                         'category': 'Shotgun',
                                                                                         'kills': 14, 'deaths': 12,
                                                                                         'kd': 1.1667, 'headshots': 0,
                                                                                         'headshot_percentage': 0,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 52,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'M870', 'category': 'Shotgun', 'kills': 3, 'deaths': 30, 'kd': 0.1, 'headshots': 0,
    'headshot_percentage': 0, 'times_chosen': 5, 'bullets_fired': 0, 'bullets_hit': 15,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'SASG-12',
                                                                                         'category': 'Shotgun',
                                                                                         'kills': 5, 'deaths': 18,
                                                                                         'kd': 0.2778, 'headshots': 1,
                                                                                         'headshot_percentage': 20,
                                                                                         'times_chosen': 2,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 26,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'M1014', 'category': 'Shotgun', 'kills': 3, 'deaths': 21, 'kd': 0.1429, 'headshots': 0,
    'headshot_percentage': 0, 'times_chosen': 1, 'bullets_fired': 0, 'bullets_hit': 13,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'SG-CQB',
                                                                                         'category': 'Shotgun',
                                                                                         'kills': 0, 'deaths': 11,
                                                                                         'kd': 0, 'headshots': 0,
                                                                                         'headshot_percentage': 0,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 2,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'M590A1', 'category': 'Shotgun', 'kills': 44, 'deaths': 70, 'kd': 0.6286, 'headshots': 0,
    'headshot_percentage': 0, 'times_chosen': 59, 'bullets_fired': 0, 'bullets_hit': 260,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'BOSG.12.2',
                                                                                         'category': 'Shotgun',
                                                                                         'kills': 1, 'deaths': 16,
                                                                                         'kd': 0.0625, 'headshots': 0,
                                                                                         'headshot_percentage': 0,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 3,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'SIX12', 'category': 'Shotgun', 'kills': 0, 'deaths': 6, 'kd': 0, 'headshots': 0,
    'headshot_percentage': 0, 'times_chosen': 0, 'bullets_fired': 0, 'bullets_hit': 0,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'SIX12 SD',
                                                                                         'category': 'Shotgun',
                                                                                         'kills': 0, 'deaths': 10,
                                                                                         'kd': 0, 'headshots': 0,
                                                                                         'headshot_percentage': 0,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 0,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'ACS12', 'category': 'Shotgun', 'kills': 4, 'deaths': 7, 'kd': 0.5714, 'headshots': 0,
    'headshot_percentage': 0, 'times_chosen': 1, 'bullets_fired': 0, 'bullets_hit': 21,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'FO-12',
                                                                                         'category': 'Shotgun',
                                                                                         'kills': 2, 'deaths': 27,
                                                                                         'kd': 0.0741, 'headshots': 1,
                                                                                         'headshot_percentage': 50,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 15,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'SMG-11', 'category': 'Machine Pistol', 'kills': 152, 'deaths': 88, 'kd': 1.7273, 'headshots': 67,
    'headshot_percentage': 44.080000000000005, 'times_chosen': 171, 'bullets_fired': 0, 'bullets_hit': 1638,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'Bearing 9',
                                                                                         'category': 'Machine Pistol',
                                                                                         'kills': 26, 'deaths': 14,
                                                                                         'kd': 1.8571, 'headshots': 7,
                                                                                         'headshot_percentage': 26.919999999999998,
                                                                                         'times_chosen': 205,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 192,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'SPSMG9', 'category': 'Machine Pistol', 'kills': 21, 'deaths': 45, 'kd': 0.4667, 'headshots': 8,
    'headshot_percentage': 38.1, 'times_chosen': 0, 'bullets_fired': 0, 'bullets_hit': 318,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'AK-74M',
                                                                                         'category': 'Assault Rifle',
                                                                                         'kills': 0, 'deaths': 52,
                                                                                         'kd': 0, 'headshots': 0,
                                                                                         'headshot_percentage': 0,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 0,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'ARX200', 'category': 'Assault Rifle', 'kills': 80, 'deaths': 72, 'kd': 1.1111, 'headshots': 38,
    'headshot_percentage': 47.5, 'times_chosen': 12, 'bullets_fired': 0, 'bullets_hit': 637,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': '.44 Mag Semi-Auto',
                                                                                         'category': 'Handgun',
                                                                                         'kills': 3, 'deaths': 4,
                                                                                         'kd': 0.75, 'headshots': 1,
                                                                                         'headshot_percentage': 33.33,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 13,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'AUG A3', 'category': 'Submachine Gun', 'kills': 7, 'deaths': 52, 'kd': 0.1346, 'headshots': 3,
    'headshot_percentage': 42.86, 'times_chosen': 0, 'bullets_fired': 0, 'bullets_hit': 40,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'TCSG12',
                                                                                         'category': 'Shotgun',
                                                                                         'kills': 9, 'deaths': 28,
                                                                                         'kd': 0.3214, 'headshots': 3,
                                                                                         'headshot_percentage': 33.33,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 30,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'F90', 'category': 'Assault Rifle', 'kills': 71, 'deaths': 28, 'kd': 2.5357, 'headshots': 34,
    'headshot_percentage': 47.89, 'times_chosen': 0, 'bullets_fired': 0, 'bullets_hit': 594,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'Super Shorty',
                                                                                         'category': 'Shotgun',
                                                                                         'kills': 4, 'deaths': 4,
                                                                                         'kd': 1, 'headshots': 1,
                                                                                         'headshot_percentage': 25,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 13,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'SDP 9mm', 'category': 'Handgun', 'kills': 19, 'deaths': 8, 'kd': 2.375, 'headshots': 1,
    'headshot_percentage': 5.26, 'times_chosen': 0, 'bullets_fired': 0, 'bullets_hit': 147,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'Commando 9',
                                                                                         'category': 'Assault Rifle',
                                                                                         'kills': 170, 'deaths': 90,
                                                                                         'kd': 1.8889, 'headshots': 68,
                                                                                         'headshot_percentage': 40,
                                                                                         'times_chosen': 0,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 1260,
                                                                                         'created': '2020-06-20T13:09:00.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'P10 RONI', 'category': 'Submachine Gun', 'kills': 303, 'deaths': 87, 'kd': 3.4828, 'headshots': 143,
    'headshot_percentage': 47.19, 'times_chosen': 0, 'bullets_fired': 0, 'bullets_hit': 3022,
    'created': '2020-06-20T13:09:00.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}, {'weapon': 'CSRX 3000',
                                                                                         'category': 'Marksman Rifle',
                                                                                         'kills': 10, 'deaths': 38,
                                                                                         'kd': 0.2632, 'headshots': 5,
                                                                                         'headshot_percentage': 50,
                                                                                         'times_chosen': 2,
                                                                                         'bullets_fired': 0,
                                                                                         'bullets_hit': 47,
                                                                                         'created': '2020-06-28T07:26:31.000Z',
                                                                                         'last_updated': '2021-05-09T12:28:02.000Z'}, {
    'weapon': 'SC3000K', 'category': 'Assault Rifle', 'kills': 128, 'deaths': 31, 'kd': 4.129, 'headshots': 46,
    'headshot_percentage': 35.94, 'times_chosen': 0, 'bullets_fired': 0, 'bullets_hit': 963,
    'created': '2021-01-15T16:11:04.000Z', 'last_updated': '2021-05-09T12:28:02.000Z'}]
